### PR TITLE
fixes issues in FF 49

### PR DESCRIPTION
**Pull request by krebbl**

### CODE REVIEW

**Comment by vkbansal** [comment]
This fixes #36 right?

**Comment by krebbl** [comment]
yes

**Comment by vkbansal** [comment]
Can you also add 

```
 document.removeEventListener('mousedown', this.handleOutsideClick);
 document.removeEventListener('ontouchstart', this.handleOutsideClick);
```

in `handleHide`?

**Comment by krebbl** [comment]
done

**Comment by krebbl** [comment]
thx a lot!

**Pull request merged**
