### PR TITLE
Tracking selected items functionality

### PR DESCRIPTION
**Pull request by acollazomayer**
Hi vkbansal!

First I want to thank you for this project, it is really useful, and saved me a lot of time. However I added a new functionality that fitted my needs and I think it is very useful. I added the ability to track selected values from different submenus inside the context menu. 

Picture this example. You may want to use the context menu for editing the styles of a graph. So you may have the y-axis range, the x-axis range and the color of the graph in different sub menus within a context menu. The graph comes initialized with the y-axis range from 1 to 10, same with the x-axis and in black color. So if you open the context menu you should be able to see what are the defaults values and if you change the the ranges or the color you want to see which are the selected values now. 

This functionality may become handy for lots of different examples, Also the ability to track the selected values is optional and the same with the default value, to activate it it is just as simple to add in the MenuItem the props, track and defaultSelection. 

I added one example on the examples page to show how this functionality is implemented and its potential.

Thank you, and hope it helps.

screen shot 2017-09-30 at 11 35 39 am

### CODE REVIEW

**Comment by vkbansal** [comment]
Hi @acollazomayer, Thanks for the PR.

I think, what you are trying to do can be achieved by maintaining some state in parent component and rendering selected/unselected within `MenuItem`.

**Comment by acollazomayer** [comment]
@vkbansal Im sorry but i didnt understand the comment, But i think it is what i did, I add a state in the `AbstractMenu` that when the menuItem is selected that state changes and changes the render of `MenuItem`

**Comment by vkbansal** [comment]
See the demo example
https://www.webpackbin.com/bins/-KvVhgkE0X9jYF-d-XZV

**Comment by acollazomayer** [comment]
@vkbansal I understand now, however i think that you are adding a responsibility to the parent component. In addition I have to change the state on every onClick, if i have a huge context menus with differents onClicks i have to chage it on everyone repeating code. 

Your answer is valid, its simple, however changing the library and adding the tracking functionality to every MenuItem, i think that makes the code a lot more readable, but that may be my biased opinion.

**Comment by vkbansal** [comment]
@acollazomayer Yours is an extreme case which will not benefit rest of the users of this library and it will just add some overhead (extra code => bundle size) for such users. The goal of this library is to be as simple and slim as possible. I believe that you will understand this.

**Pull request closed without merging**
