### PR TITLE
Adjust context menu position for bootstrap modal

### PR DESCRIPTION
**Pull request by akash247**
The user can give posX and posY as props to adjust the current position of the context menu.

### CODE REVIEW

**Comment by akash247** [comment]
Hi @vkbansal, I am not seeing the merged code after executing `npm install --save react-contextmenu`. Can you tell me what is the problem here?

**Comment by vkbansal** [comment]
It is not published yet. Will publish in some time

**Comment by akash247** [comment]
Ok thanks @vkbansal for a quick reply :) 
It will be really helpful if I can get an estimated date.
Thanks again.

**Comment by vkbansal** [comment]
Published as 2.9.3

**Comment by akash247** [comment]
Thanks :)

**Pull request merged**
