### PR TITLE
if `props.collect` returns Promise, resolve it before `showMenu`

### PR DESCRIPTION
**Pull request by redguardtoo**
the collect may need talk to back end server to fetch some data for contextmenu.

If `props.collect` is a Promise, resolve it before calling `showMenu`

### CODE REVIEW

**Comment by vkbansal** [comment]
Can you please explain with an example (possibly real world), how this can be helpful?

**Comment by redguardtoo** [comment]
When right click the a table cell, I need read value of that cell, then I need send that value to backend, backend will create menu items for that cell.

So until the backend send me back the data, there is nothing to display on menu items.

I'm building a financial software where each cell represents cash forecast in one day. Depending type and date of cash forecast, different validations will be applied.

**Comment by vkbansal** [comment]
@Seldaek what's your take on this?

**Comment by vkbansal** [comment]
@redguardtoo There are lint errors. Can you fix those?

**Comment by redguardtoo** [comment]
Hi, @vkbansal , I fixed the lint errors

**Comment by Seldaek** [comment]
@vkbansal seems like a reasonable small addition to me.

**Pull request merged**
