### PR TITLE
Context menu on tablets

### PR DESCRIPTION
**Pull request by bjarkig82**
Hello,

Thank you for your contribution, it has helped me a lot. I was designing an app that is to be used in a tablet but there is no right mouse button on tablets :-)

I forked your module and altered it so it would open the context menu if the mouse (or finger) is helt down on a given time. To activate it, put the prop 'holdToDisplay={[milliseconds]}' in the container.  I activated this feature in the simple-menu example.

I hope you like this modification.

Best regards,
Bjarki

### CODE REVIEW

**Comment by vkbansal** [comment]
Thanks for the PR. :+1: 

I'm a bit occupied right now. I'll have a look at this ASAP

**Comment by vkbansal** [comment]
LGTM. Merging

**Comment by onelson** [comment]
I don't have much in the way of details for you, but just a heads up that this seems to be swallowing click events (even without setting `holdToDisplay`) on Windows 8.1 Chrome which has both mouse and touch support. Firefox on Windows 8.1 seems OK, so it's probably something fussy with Chrome on the event handling.

For now, downgrading to 1.5.0 is working for me.

**Comment by vkbansal** [comment]
@onelson on which version are you facing the issue?

**Comment by onelson** [comment]
1.6.3, and 1.6.0

**Comment by vkbansal** [comment]
@bjarkig82 Can you help us out here?

**Comment by bjarkig82** [comment]
I'm a bit busy this week. I'll see if I can take a look at this next weekend :)

**Comment by vkbansal** [comment]
@onelson can you check if #42 works for you?

**Comment by onelson** [comment]
I'll have to setup a test app for this -- can't drop this in on our app since we still depend on `monitor` which I don't think is available in 2.x. I'll get back to you.

**Pull request merged**
