### PR TITLE
Allow working on browsers without requestAnimationFrame

### PR DESCRIPTION
**Pull request by Seldaek**
Would be nice to possibly support IE9+. I understand you can't guarantee support, but if you accept patches I'll try and make it work.

### CODE REVIEW

**Comment by Seldaek** [comment]
I tried my patched version and I can confirm that seems to make it work fine in IE9

**Comment by vkbansal** [comment]
I'm not in the favour of supporting old/legacy browsers. The major reason for bumping to 2.x was [dropping the support for IE9](https://github.com/vkbansal/react-contextmenu/releases/tag/v2.0.0-alpha.1). But I'm open for discussion.

**Comment by Seldaek** [comment]
Well I agree that these days it's usually not worth the trouble to support IE10 and 9, but given the effort here is basically zero, I think it's ok to support them. If it breaks in a future version that's fine, it's life, you shouldn't offer any guarantees. But not supporting it on principle even though the fix is really tiny I think it's a bit sad.

**Comment by vkbansal** [comment]
Yes, I agree that the effort is almost zero in this case. But I believe that if someone needs to use this component in IE9/10, they must be responsible for polyfilling `requestAnimationFrame` instead of the library itself. Also `setTimeout` is not apt polyfill for `requestAnimationFrame`. 

Frankly I'm not comfortable with this, but if you can take responsibility for the support, then I'll go ahead and merge this PR.

**Comment by Seldaek** [comment]
Well.. I don't know about providing support in the long run, but just FYI there is already the same workaround in https://github.com/vkbansal/react-contextmenu/blob/master/src/SubMenu.js#L37 - which is why I thought it'd be ok to do the same somewhere else, even though the APIs are not strictly equivalent.

**Comment by vkbansal** [comment]
oops

**Comment by Seldaek** [comment]
;)

Thanks

**Pull request merged**
